{
	"version": 1617436429,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/bg_menu-default-000.jpg",
		"images/select-sheet0.png",
		"images/logo_menu-sheet0.png",
		"images/black_bg-default-000.jpg",
		"images/bg_day-default-000.jpg",
		"images/grasswalk.png",
		"images/labyehtize-sheet0.png",
		"images/asansor-sheet0.png",
		"images/enemy-sheet0.png",
		"images/coin-sheet0.png",
		"images/finish-sheet0.png",
		"images/player1_sprite-sheet0.png",
		"images/player1_sprite-sheet1.png",
		"images/grasswalk_snowy.png",
		"images/bg_snow-default-000.jpg",
		"images/bg_rainy-default-000.jpg",
		"images/asphalt_grasswalk.png",
		"images/city_bg-default-000.jpg",
		"images/jungle_bg-default-000.jpg",
		"images/bg_loading-default-000.jpg",
		"images/loading_black-sheet0.png",
		"images/loadingbar.png",
		"images/sand_grasswalk.png",
		"images/bg_beach-default-000.jpg",
		"images/wood_grasswalk.png",
		"images/chip_bg-default-000.jpg",
		"images/castle_grasswalk.png",
		"images/godazeh_hot-sheet0.png",
		"images/castle_bg-default-000.jpg",
		"images/bg_bossbattle-default-000.jpg",
		"images/health_boss.png",
		"images/boss1-sheet0.png",
		"images/boss1-sheet1.png",
		"images/desert_bg-default-000.jpg",
		"images/boss2-sheet0.png",
		"images/boss2-sheet1.png",
		"images/boss2-sheet2.png",
		"images/night_bg-sheet0.png",
		"images/finalboss-sheet0.png",
		"images/dhokamhe-sheet0.png",
		"images/bomb-sheet0.png",
		"images/player_ending-sheet0.png",
		"images/baby_ending-sheet0.png",
		"images/poses-sheet0.png",
		"images/soild_not_view-sheet0.png",
		"images/outside_layout-default-000.jpg",
		"images/save_level-sheet0.png",
		"media/alert_1.ogg",
		"media/coin_1.ogg",
		"media/jump.ogg",
		"media/win.ogg",
		"media/wood-tap_1.ogg",
		"media/zoop_1.ogg",
		"media/lose.ogg",
		"media/01 start menu.ogg",
		"media/02 light day.ogg",
		"media/04 snow winter.ogg",
		"media/05 rain day.ogg",
		"media/06 castle.ogg",
		"media/07 bass battle.ogg",
		"media/08 city.ogg",
		"media/09 jungle.ogg",
		"media/10 sea.ogg",
		"media/11 ship.ogg",
		"media/12 desret.ogg",
		"media/12 night dark.ogg",
		"media/13 fires of a revolution (final boss).ogg",
		"media/14 ending.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}